-- THE LIST v4
-- Player stats + rating history

create table if not exists public.rating_history (
  id bigint generated by default as identity primary key,
  level_id bigint not null references public.levels(id) on delete cascade,
  rating double precision not null,
  comparisons integer not null,
  created_at timestamptz not null default now()
);

create index if not exists rating_history_level_idx
  on public.rating_history(level_id, created_at desc);

alter table public.rating_history enable row level security;

drop policy if exists "Public can view rating history" on public.rating_history;
create policy "Public can view rating history"
on public.rating_history
for select
to anon, authenticated
using (true);

revoke insert, update, delete
on public.rating_history
from anon, authenticated;

-- Recreate comparison RPC so every vote records both levels' new ratings.
create or replace function public.submit_comparison(
  p_level_a bigint,
  p_level_b bigint,
  p_winner bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  a public.levels;
  b public.levels;
  ea double precision;
  eb double precision;
  new_a double precision;
  new_b double precision;
  k constant double precision := 32;
begin
  if p_level_a = p_level_b then
    raise exception 'A level cannot be compared with itself';
  end if;

  if p_winner <> p_level_a and p_winner <> p_level_b then
    raise exception 'Winner must be one of the two compared levels';
  end if;

  select * into a from public.levels where id = p_level_a for update;
  select * into b from public.levels where id = p_level_b for update;

  if a.id is null or b.id is null then
    raise exception 'One or both levels do not exist';
  end if;

  ea := 1 / (1 + power(10, (b.rating - a.rating) / 400));
  eb := 1 - ea;

  if p_winner = p_level_a then
    new_a := a.rating + k * (1 - ea);
    new_b := b.rating + k * (0 - eb);
  else
    new_a := a.rating + k * (0 - ea);
    new_b := b.rating + k * (1 - eb);
  end if;

  update public.levels
  set rating = new_a, comparisons = comparisons + 1
  where id = a.id;

  update public.levels
  set rating = new_b, comparisons = comparisons + 1
  where id = b.id;

  insert into public.comparisons(level_a, level_b, winner)
  values (p_level_a, p_level_b, p_winner);

  insert into public.rating_history(level_id, rating, comparisons)
  values
    (a.id, new_a, a.comparisons + 1),
    (b.id, new_b, b.comparisons + 1);

  return jsonb_build_object(
    'level_a', p_level_a,
    'level_b', p_level_b,
    'winner', p_winner,
    'rating_a', new_a,
    'rating_b', new_b
  );
end;
$$;

grant execute on function public.submit_comparison(bigint,bigint,bigint)
to anon, authenticated;

-- Helpful player statistics view.
drop view if exists public.player_stats;

create view public.player_stats as
select
  p.id as player_id,
  p.username,
  count(c.id)::integer as levels_beaten,
  coalesce(max(l.rating), 0)::double precision as hardest_rating,
  coalesce(avg(l.rating), 0)::double precision as average_rating,
  coalesce(sum(greatest(0, l.rating - 1500)), 0)::double precision as difficulty_score,
  min(c.created_at) as first_completion_at,
  max(c.created_at) as latest_completion_at
from public.players p
left join public.completions c
  on c.player_id = p.id
 and c.status = 'approved'
left join public.levels l
  on l.id = c.level_id
where p.username is not null
group by p.id, p.username;

grant select on public.player_stats to anon, authenticated;
