-- THE LIST v3 migration
-- Run after your existing The List SQL.
-- This adds richer level metadata, YouTube completion review, owner deletion,
-- and player/level profile data.

alter table public.players alter column username drop not null;
alter table public.levels add column if not exists creator text;
alter table public.levels add column if not exists description text;
alter table public.levels add column if not exists song_name text;
alter table public.levels add column if not exists gd_difficulty text;

create table if not exists public.completions (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  level_id bigint not null references public.levels(id) on delete cascade,
  youtube_url text not null,
  status text not null default 'pending' check(status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id),
  unique(player_id,level_id)
);

alter table public.completions enable row level security;
drop policy if exists "Public can view completions" on public.completions;
create policy "Public can view completions" on public.completions for select to anon,authenticated using (status='approved' or exists(select 1 from public.owner_users where user_id=auth.uid()) or exists(select 1 from public.players p where p.id=player_id and p.user_id=auth.uid()));

revoke insert,update,delete on public.completions from anon,authenticated;

create or replace function public.submit_completion(p_level_id bigint,p_youtube_url text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.players;
begin
  if auth.uid() is null then raise exception 'You must be logged in'; end if;
  select * into p from public.players where user_id=auth.uid();
  if p.id is null or p.username is null then raise exception 'Choose a username first'; end if;
  if not exists(select 1 from public.levels where id=p_level_id) then raise exception 'That level does not exist'; end if;
  if p_youtube_url !~* '^https?://(www\.)?(youtube\.com|youtu\.be)/' then raise exception 'Please submit a YouTube link'; end if;
  insert into public.completions(player_id,level_id,youtube_url,status)
  values(p.id,p_level_id,p_youtube_url,'pending')
  on conflict(player_id,level_id) do update set youtube_url=excluded.youtube_url,status='pending',created_at=now(),reviewed_at=null,reviewed_by=null;
  return jsonb_build_object('saved',true,'status','pending');
end; $$;

create or replace function public.review_completion(p_completion_id bigint,p_status text)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.owner_users where user_id=auth.uid()) then raise exception 'Only the owner can review completions'; end if;
  if p_status not in ('approved','rejected') then raise exception 'Invalid review status'; end if;
  update public.completions set status=p_status,reviewed_at=now(),reviewed_by=auth.uid() where id=p_completion_id;
  if not found then raise exception 'Submission not found'; end if;
  return jsonb_build_object('saved',true,'status',p_status);
end; $$;

create or replace function public.delete_level(p_level_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.owner_users where user_id=auth.uid()) then raise exception 'Only the owner can delete levels'; end if;
  delete from public.levels where id=p_level_id;
  if not found then raise exception 'Level not found'; end if;
  return jsonb_build_object('deleted',true,'level_id',p_level_id);
end; $$;

grant execute on function public.submit_completion(bigint,text) to authenticated;
grant execute on function public.review_completion(bigint,text) to authenticated;
grant execute on function public.delete_level(bigint) to authenticated;

drop view if exists public.player_leaderboard;
create view public.player_leaderboard as
select p.id as player_id,p.username,
 count(c.id)::integer as levels_beaten,
 coalesce(sum(greatest(0,2000-l.rating)),0)::double precision as difficulty_score
from public.players p
left join public.completions c on c.player_id=p.id and c.status='approved'
left join public.levels l on l.id=c.level_id
where p.username is not null
group by p.id,p.username;
grant select on public.player_leaderboard to anon,authenticated;
